// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core`, `guarded`, `new`, `on_core`, `parse_json`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// 初始化核心。`data_dir` 是 docs/design.md § 10 的数据目录（Windows：%APPDATA%/AcpAgentClient）。
/// 幂等：热重启后再次调用只重发一条 `acp/agent_state: core_ready`。返回 JSON `{dataDir, coreVersion, logPath}`。
Future<String> coreInit({required String dataDir}) =>
    RustLib.instance.api.crateApiCoreInit(dataDir: dataDir);

/// R0 往返命令：Dart 调过来、核心回 JSON `{pong, sequence, coreVersion}`。
Future<String> ping({required String echo}) =>
    RustLib.instance.api.crateApiPing(echo: echo);

/// 按 settings.json 的 `agent_servers[agent_id]` 拉起 agent 并完成 `initialize`；已连接的先断开。
/// `cwd` 是 agent 进程的工作目录（可选）。返回 `{agentId, initialize}`（`initialize` 是 InitializeResponse 原样 JSON）。
Future<String> agentConnect({required String agentId, String? cwd}) =>
    RustLib.instance.api.crateApiAgentConnect(agentId: agentId, cwd: cwd);

/// 关掉 agent（先关 stdin 等它自己退，超时结束进程树）。退出事件仍经 `acp/agent_state: exited` 推出。
Future<String> agentDisconnect({required String agentId}) =>
    RustLib.instance.api.crateApiAgentDisconnect(agentId: agentId);

/// `session/new`。回 `-32000` 时抛 `auth_required`（authMethods 已经 `acp/agent_state: auth_required` 推出）。
/// 返回 NewSessionResponse 原样 JSON。
Future<String> sessionNew({required String agentId, required String cwd}) =>
    RustLib.instance.api.crateApiSessionNew(agentId: agentId, cwd: cwd);

/// `session/prompt`。`prompt` 是 `ContentBlock[]` 的 JSON 字符串；本轮的 `session/update` 经事件流推出，
/// 本函数在回合结束时返回 PromptResponse 原样 JSON（stopReason + usage）。
Future<String> sessionPrompt({
  required String agentId,
  required String sessionId,
  required String prompt,
}) => RustLib.instance.api.crateApiSessionPrompt(
  agentId: agentId,
  sessionId: sessionId,
  prompt: prompt,
);

/// `session/cancel`：挂起的权限请求由核心自动回 `cancelled`；未完成的工具卡由前端本地标 cancelled（核心不伪造状态）。
/// 返回 `{cancelledRequestIds}`。
Future<String> sessionCancel({
  required String agentId,
  required String sessionId,
}) => RustLib.instance.api.crateApiSessionCancel(
  agentId: agentId,
  sessionId: sessionId,
);

/// `session/set_mode`（老 agent 的回退；configOptions 优先）。
Future<String> sessionSetMode({
  required String agentId,
  required String sessionId,
  required String modeId,
}) => RustLib.instance.api.crateApiSessionSetMode(
  agentId: agentId,
  sessionId: sessionId,
  modeId: modeId,
);

/// `session/set_config_option`。`value` 是 `SessionConfigOptionValue` 的 JSON（`{"type":"select","value":"x"}` /
/// `{"type":"boolean","value":true}`）。返回全量 configOptions（SetSessionConfigOptionResponse 原样 JSON）。
Future<String> sessionSetConfigOption({
  required String agentId,
  required String sessionId,
  required String configId,
  required String value,
}) => RustLib.instance.api.crateApiSessionSetConfigOption(
  agentId: agentId,
  sessionId: sessionId,
  configId: configId,
  value: value,
);

/// 回应 `acp/client_request`（`session/request_permission` / `elicitation/create`）。`request_id` 原样回传事件里的值，
/// `response` 是对应 Response 的 JSON 字符串。
Future<String> acpRespond({
  required String agentId,
  required String requestId,
  required String response,
}) => RustLib.instance.api.crateApiAcpRespond(
  agentId: agentId,
  requestId: requestId,
  response: response,
);

/// agent 型认证：`authenticate(methodId)`，agent 自己开浏览器；成功后由前端重试 `session_new`。
Future<String> authenticate({
  required String agentId,
  required String methodId,
}) => RustLib.instance.api.crateApiAuthenticate(
  agentId: agentId,
  methodId: methodId,
);

/// terminal 型认证：在可见终端（pty）里跑方法给的命令，输出经 `acp/terminal_output`（source = auth）推出，
/// 键盘输入走 `terminal_write`；进程退出后核心自动重试 `session/new`。返回 `{terminalId, exitStatus, session}`。
Future<String> terminalAuthRun({
  required String agentId,
  required String methodId,
  required String cwd,
}) => RustLib.instance.api.crateApiTerminalAuthRun(
  agentId: agentId,
  methodId: methodId,
  cwd: cwd,
);

/// 往终端写键盘输入（UTF-8 文本原样写进 pty）。R4 的本地 shell 四命令之一，terminal auth 需要它所以 R1 先出。
Future<String> terminalWrite({
  required String terminalId,
  required String data,
}) => RustLib.instance.api.crateApiTerminalWrite(
  terminalId: terminalId,
  data: data,
);

/// 开一个本地 shell（系统默认 shell）：输出经 `acp/terminal_output`（source = local）推出。
/// `cols` / `rows` 是初始尺寸（之后由 `terminal_resize` 跟着视口走）。返回 `{terminalId, cwd, program}`。
Future<String> terminalOpen({
  required String cwd,
  required int cols,
  required int rows,
}) =>
    RustLib.instance.api.crateApiTerminalOpen(cwd: cwd, cols: cols, rows: rows);

/// 视口尺寸变化（xterm 报出的列 × 行）。
Future<String> terminalResize({
  required String terminalId,
  required int cols,
  required int rows,
}) => RustLib.instance.api.crateApiTerminalResize(
  terminalId: terminalId,
  cols: cols,
  rows: rows,
);

/// 结束终端里的进程但不释放（画板 23 的停止方块 = `terminal/kill` 语义；退出状态仍经 `acp/terminal_output` 推出）。
/// agent 建的终端也可以用它停（agent 的 `terminal/wait_for_exit` 会随之返回）。
Future<String> terminalKill({required String terminalId}) =>
    RustLib.instance.api.crateApiTerminalKill(terminalId: terminalId);

/// 关掉一个终端（认证页的停止方块与本地 shell 标签同一条命令）：还在跑就先结束进程，然后释放句柄；退出事件仍经 `acp/terminal_output` 推出。
Future<String> terminalClose({required String terminalId}) =>
    RustLib.instance.api.crateApiTerminalClose(terminalId: terminalId);

/// 应用退出前的收尾：释放全部终端（还在跑的先结束）、断开全部 agent（超时结束进程树）、停掉目录监视。
/// 返回 `{terminals, agents}`。Dart 侧在 `AppLifecycleListener.onExitRequested` 里等它回来再放行退出。
Future<String> coreShutdown() => RustLib.instance.api.crateApiCoreShutdown();

/// 读 `settings.json`（不存在 → `{agent_servers: {}}`）。
Future<String> agentSettingsGet() =>
    RustLib.instance.api.crateApiAgentSettingsGet();

/// 覆盖 `agent_servers[agent_id]`（`server` 是 `{type: "custom", command, args, env}` 的 JSON），临时文件 + rename 落盘；
/// 返回落盘后的全量设置。
Future<String> agentSettingsSet({
  required String agentId,
  required String server,
}) => RustLib.instance.api.crateApiAgentSettingsSet(
  agentId: agentId,
  server: server,
);

/// 删掉 `agent_servers[agent_id]`（custom 型从设置页删除；registry 型请走 `registry_remove`，它还会清 `agents/<id>/`）。
/// 已连接的先断开。返回落盘后的全量设置。
Future<String> agentSettingsRemove({required String agentId}) =>
    RustLib.instance.api.crateApiAgentSettingsRemove(agentId: agentId);

/// 从 Zed 的 `settings.json` 导入 `agent_servers`（JSONC，同名不覆盖）。返回 `{report: {path, imported, skipped, invalid}, settings}`；
/// 找不到 Zed 的文件时抛 `settings`。
Future<String> agentSettingsImportZed() =>
    RustLib.instance.api.crateApiAgentSettingsImportZed();

/// 开发期排查：每个已连接 agent 的 droppedUpdates / 退出状态 / 挂起请求。
Future<String> agentsStatus() => RustLib.instance.api.crateApiAgentsStatus();

/// registry 列表：`{agents: [{id, name, version, description, repository?, website?, iconSvg?, distribution, supported, package?,
/// installed: {kind, version, installedVersion?, command, args, env, authStatus, agentInfo?, installedAt} | null, installing, custom: {command, args, env} | null}],
/// fetching, fetchError?, fetchedAt?, node: {system?, systemError?, managed?, minVersion}, paths: {dataDir, logPath, zedSettingsPath?}}`。
/// 只读缓存，不联网（联网是 `registry_refresh`）；已安装 / custom 条目排前面。
Future<String> registryList() => RustLib.instance.api.crateApiRegistryList();

/// 联网拉 `registry.json`（1 小时节流，`force` 跳过）并顺手补图标；失败不清缓存、错误进 `fetchError`。返回同 `registry_list`。
Future<String> registryRefresh({required bool force}) =>
    RustLib.instance.api.crateApiRegistryRefresh(force: force);

/// 后台安装一个 registry 条目（npx：resolve / write_settings / handshake；binary：download / verify / extract），立即返回
/// `{agentId, started}`；进度与收尾（done / failed / cancelled）经 `registry/progress` 推出。已在安装中抛 `invalid_argument`。
Future<String> registryInstall({required String agentId}) =>
    RustLib.instance.api.crateApiRegistryInstall(agentId: agentId);

/// 取消正在跑的安装；返回 `{agentId, cancelled}`（没有在装的 `cancelled: false`）。
Future<String> registryCancelInstall({required String agentId}) =>
    RustLib.instance.api.crateApiRegistryCancelInstall(agentId: agentId);

/// Remove：取消安装、断开连接、删 settings 条目、只删 `agents/<id>/`（规则 7）。返回同 `registry_list` 再加 `removed`。
Future<String> registryRemove({required String agentId}) =>
    RustLib.instance.api.crateApiRegistryRemove(agentId: agentId);

/// Node 状态：`{system: {version, path}?, systemError?, managed: {version, path}?, minVersion}`。
Future<String> nodeStatus() => RustLib.instance.api.crateApiNodeStatus();

/// 下载受管 Node v24.11.0 到数据目录 `node/`（进度 `agentId: null`，步骤 node_download / node_extract），完成后返回 Node 状态。
Future<String> nodeDownload() => RustLib.instance.api.crateApiNodeDownload();

/// 列一层目录。`root` 是当前项目目录，`path` 必须在它之内（越界报 `fs`）。
/// 返回 `{path, entries: [{name, path, parent, isDir, size}]}`，目录在前、各自按名排序。
Future<String> fsListDir({required String root, required String path}) =>
    RustLib.instance.api.crateApiFsListDir(root: root, path: path);

/// 按名字子串搜索（`@` 提及）。返回 `{files, directories, truncated}`；`query` 为空时不遍历、直接回空。
Future<String> fsSearch({
  required String root,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiFsSearch(
  root: root,
  query: query,
  limit: limit,
);

/// 查看器读文件（画板 60，R4）：`{path, text, size, lines, binary, truncated}`；超过 2 MiB 只给前一段并标 `truncated`，
/// 含 NUL 的按二进制处理（`text` 为空）。`path` 必须在 `root` 之内。
Future<String> fsRead({required String root, required String path}) =>
    RustLib.instance.api.crateApiFsRead(root: root, path: path);

/// 监视项目目录（R4）：流命令——每批去抖后的变化推一条 `{root, dirs: [绝对路径…], git}`（`dirs` 是内容变了的目录，
/// `git` = `.git` 之下有变化）；Dart 侧取消流即停止。同一 `root` 再次调用替换旧监视器。
Stream<String> fsWatch({required String root}) =>
    RustLib.instance.api.crateApiFsWatch(root: root);

/// 停掉某个根的监视；没在监视也不报错。返回 `{root, removed}`。
Future<String> fsUnwatch({required String root}) =>
    RustLib.instance.api.crateApiFsUnwatch(root: root);

/// 文件树的 git 状态徽章（画板 60，所有者裁定 2026-09-15）：`{available, isRepo, root, entries: [{path, badge, code}]}`。
/// 非仓库 / 无 git 不报错，`entries` 为空。
Future<String> gitStatus({required String cwd}) =>
    RustLib.instance.api.crateApiGitStatus(cwd: cwd);

/// 本地分支列表：`{available, isRepo, current, branches: [{name, author, when, subject}]}`。
/// 找不到 `git`（`available: false`）或目录不是仓库（`isRepo: false`）都不是错误——前端据此把顶栏分支区整块隐藏。
Future<String> gitBranches({required String cwd}) =>
    RustLib.instance.api.crateApiGitBranches(cwd: cwd);

/// `git switch <branch>`；返回切换后的分支列表。git 报错（例如有未提交改动）时抛 `fs`，消息是 git 自己的 stderr。
Future<String> gitSwitch({required String cwd, required String branch}) =>
    RustLib.instance.api.crateApiGitSwitch(cwd: cwd, branch: branch);

/// `git switch -c <branch>`（从当前 HEAD 拉）；返回切换后的分支列表。
Future<String> gitCreateBranch({required String cwd, required String branch}) =>
    RustLib.instance.api.crateApiGitCreateBranch(cwd: cwd, branch: branch);

/// `git diff`：给了 `base` 就是 `git diff <base>...HEAD`，否则是工作区相对 HEAD 的改动。
/// 返回 `{available, isRepo, command, text, truncated}`；输出超过 200 KiB 截断（整份 diff 进 prompt 会顶爆上下文）。
Future<String> gitDiff({required String cwd, String? base}) =>
    RustLib.instance.api.crateApiGitDiff(cwd: cwd, base: base);

/// 最近项目列表：`{projects: [{path, name, openedAt}]}`（按 `openedAt` 倒序）。
Future<String> workspaceRecent() =>
    RustLib.instance.api.crateApiWorkspaceRecent();

/// 打开一个本地目录作为项目（`session/new` 的 cwd）：写进最近列表，返回 `{project, projects}`。
/// 目录不存在或不是目录时抛 `settings`。
Future<String> workspaceOpen({required String path}) =>
    RustLib.instance.api.crateApiWorkspaceOpen(path: path);

/// 会话索引全量：`{sessions: [{agentId, sessionId, title?, cwd?, createdAt, updatedAt, messageCount}]}`。
Future<String> sessionIndexList() =>
    RustLib.instance.api.crateApiSessionIndexList();

/// 新增 / 更新一条会话索引（`entry` 是上面那个形状的 JSON 字符串）；返回全量列表。
/// `createdAt` 只在新增时写；`updatedAt` 省略或为 0 时由核心打当前时间。
Future<String> sessionIndexUpsert({required String entry}) =>
    RustLib.instance.api.crateApiSessionIndexUpsert(entry: entry);

/// 移除一条会话索引；返回全量列表。向 agent 发 `session/delete` 是 R6 的事。
Future<String> sessionIndexRemove({
  required String agentId,
  required String sessionId,
}) => RustLib.instance.api.crateApiSessionIndexRemove(
  agentId: agentId,
  sessionId: sessionId,
);

/// 窗口 UI 状态：`{sidebarWidth?, rightPanelWidth?}`。没存过的字段是 null，缺省宽度在前端 token 里。
Future<String> uiStateGet() => RustLib.instance.api.crateApiUiStateGet();

/// 合并写窗口 UI 状态（`patch` 是上面那个形状的 JSON 字符串，只给要改的字段）；返回落盘后的全量状态。
Future<String> uiStateSet({required String patch}) =>
    RustLib.instance.api.crateApiUiStateSet(patch: patch);

/// `acp/session_update`：`{agentId, sessionId, update, _meta?}`，即 SessionNotification 原样 JSON 加 `agentId`。
Stream<String> sessionUpdateStream() =>
    RustLib.instance.api.crateApiSessionUpdateStream();

/// `acp/client_request`：`{agentId, requestId, method, params}`；`requestId` 为 null 的是通知
/// （`elicitation/complete`、`$/cancel_request`），不需回应。
Stream<String> clientRequestStream() =>
    RustLib.instance.api.crateApiClientRequestStream();

/// `acp/agent_state`：core_ready / spawned / initialized / auth_required / authenticating / update_dropped / exited。
Stream<String> agentStateStream() =>
    RustLib.instance.api.crateApiAgentStateStream();

/// `acp/terminal_output`：`{terminalId, source, bytes}`（base64）或 `{terminalId, source, exitStatus}`。
Stream<String> terminalOutputStream() =>
    RustLib.instance.api.crateApiTerminalOutputStream();

/// `acp/traffic`：`{agentId, direction, line, ts}`，`line` 是脱敏后的原始 JSON-RPC 行（或 stderr 行）。
Stream<String> trafficStream() => RustLib.instance.api.crateApiTrafficStream();

/// `registry/progress`：`{agentId?, kind, step, done?, total?, detail?, error?}`（R5；`agentId` 为 null 是受管 Node）。
Stream<String> registryProgressStream() =>
    RustLib.instance.api.crateApiRegistryProgressStream();

/// 未送达（Dart 未订阅或流已关闭）的事件计数，供开发期排查。
BigInt droppedEventCount() => RustLib.instance.api.crateApiDroppedEventCount();

/// 跨桥的错误形状：Dart 侧作为 `BridgeError` 异常抛出。`code` 是 `CoreError::code()` 的稳定短码。
class BridgeError implements FrbException {
  final String code;
  final String message;

  const BridgeError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}
