// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `core`, `guarded`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// 初始化核心。`data_dir` 是 docs/design.md § 10 的数据目录（Windows：%APPDATA%/AcpAgentClient）。
/// 幂等：热重启后再次调用只重发一条 `acp/agent_state: core_ready`。返回 JSON `{dataDir, coreVersion}`。
Future<String> coreInit({required String dataDir}) =>
    RustLib.instance.api.crateApiCoreInit(dataDir: dataDir);

/// R0 往返命令：Dart 调过来、核心回 JSON `{pong, sequence, coreVersion}`。
Future<String> ping({required String echo}) =>
    RustLib.instance.api.crateApiPing(echo: echo);

/// `acp/session_update`：`{agentId, sessionId, update}`，`update` 是 SessionNotification 原样 JSON。
Stream<String> sessionUpdateStream() =>
    RustLib.instance.api.crateApiSessionUpdateStream();

/// `acp/client_request`：`{agentId, requestId, method, params}`。
Stream<String> clientRequestStream() =>
    RustLib.instance.api.crateApiClientRequestStream();

/// `acp/agent_state`：连接生命周期；R0 只有 `core_ready`。
Stream<String> agentStateStream() =>
    RustLib.instance.api.crateApiAgentStateStream();

/// `acp/terminal_output`：`{terminalId, source, bytes}`（R4 才有内容）。
Stream<String> terminalOutputStream() =>
    RustLib.instance.api.crateApiTerminalOutputStream();

/// `acp/traffic`：脱敏后的原始 JSON-RPC 行（R1 才有内容）。
Stream<String> trafficStream() => RustLib.instance.api.crateApiTrafficStream();

/// 未送达（Dart 未订阅或流已关闭）的事件计数，供开发期排查。
BigInt droppedEventCount() => RustLib.instance.api.crateApiDroppedEventCount();

/// 跨桥的错误形状：Dart 侧作为 `BridgeError` 异常抛出。
class BridgeError implements FrbException {
  final String code;
  final String message;

  const BridgeError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}
