// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1777903966;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'acp_bridge',
        ioDirectory: 'rust/bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAcpRespond({
    required String agentId,
    required String requestId,
    required String response,
  });

  Future<String> crateApiAgentConnect({required String agentId, String? cwd});

  Future<String> crateApiAgentDisconnect({required String agentId});

  Future<String> crateApiAgentSettingsGet();

  Future<String> crateApiAgentSettingsSet({
    required String agentId,
    required String server,
  });

  Stream<String> crateApiAgentStateStream();

  Future<String> crateApiAgentsStatus();

  Future<String> crateApiAuthenticate({
    required String agentId,
    required String methodId,
  });

  Stream<String> crateApiClientRequestStream();

  Future<String> crateApiCoreInit({required String dataDir});

  BigInt crateApiDroppedEventCount();

  Future<String> crateApiFsListDir({
    required String root,
    required String path,
  });

  Future<String> crateApiFsSearch({
    required String root,
    required String query,
    required int limit,
  });

  Future<String> crateApiGitBranches({required String cwd});

  Future<String> crateApiGitCreateBranch({
    required String cwd,
    required String branch,
  });

  Future<String> crateApiGitDiff({required String cwd, String? base});

  Future<String> crateApiGitSwitch({
    required String cwd,
    required String branch,
  });

  Future<void> crateApiInitApp();

  Future<String> crateApiPing({required String echo});

  Future<String> crateApiSessionCancel({
    required String agentId,
    required String sessionId,
  });

  Future<String> crateApiSessionIndexList();

  Future<String> crateApiSessionIndexRemove({
    required String agentId,
    required String sessionId,
  });

  Future<String> crateApiSessionIndexUpsert({required String entry});

  Future<String> crateApiSessionNew({
    required String agentId,
    required String cwd,
  });

  Future<String> crateApiSessionPrompt({
    required String agentId,
    required String sessionId,
    required String prompt,
  });

  Future<String> crateApiSessionSetConfigOption({
    required String agentId,
    required String sessionId,
    required String configId,
    required String value,
  });

  Future<String> crateApiSessionSetMode({
    required String agentId,
    required String sessionId,
    required String modeId,
  });

  Stream<String> crateApiSessionUpdateStream();

  Future<String> crateApiTerminalAuthRun({
    required String agentId,
    required String methodId,
    required String cwd,
  });

  Stream<String> crateApiTerminalOutputStream();

  Future<String> crateApiTerminalWrite({
    required String terminalId,
    required String data,
  });

  Stream<String> crateApiTrafficStream();

  Future<String> crateApiWorkspaceOpen({required String path});

  Future<String> crateApiWorkspaceRecent();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAcpRespond({
    required String agentId,
    required String requestId,
    required String response,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(requestId, serializer);
          sse_encode_String(response, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAcpRespondConstMeta,
        argValues: [agentId, requestId, response],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAcpRespondConstMeta => const TaskConstMeta(
    debugName: "acp_respond",
    argNames: ["agentId", "requestId", "response"],
  );

  @override
  Future<String> crateApiAgentConnect({required String agentId, String? cwd}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_opt_String(cwd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAgentConnectConstMeta,
        argValues: [agentId, cwd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentConnectConstMeta => const TaskConstMeta(
    debugName: "agent_connect",
    argNames: ["agentId", "cwd"],
  );

  @override
  Future<String> crateApiAgentDisconnect({required String agentId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAgentDisconnectConstMeta,
        argValues: [agentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentDisconnectConstMeta =>
      const TaskConstMeta(debugName: "agent_disconnect", argNames: ["agentId"]);

  @override
  Future<String> crateApiAgentSettingsGet() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAgentSettingsGetConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentSettingsGetConstMeta =>
      const TaskConstMeta(debugName: "agent_settings_get", argNames: []);

  @override
  Future<String> crateApiAgentSettingsSet({
    required String agentId,
    required String server,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(server, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAgentSettingsSetConstMeta,
        argValues: [agentId, server],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentSettingsSetConstMeta => const TaskConstMeta(
    debugName: "agent_settings_set",
    argNames: ["agentId", "server"],
  );

  @override
  Stream<String> crateApiAgentStateStream() {
    final sink = RustStreamSink<String>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_String_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAgentStateStreamConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAgentStateStreamConstMeta =>
      const TaskConstMeta(debugName: "agent_state_stream", argNames: ["sink"]);

  @override
  Future<String> crateApiAgentsStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAgentsStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAgentsStatusConstMeta =>
      const TaskConstMeta(debugName: "agents_status", argNames: []);

  @override
  Future<String> crateApiAuthenticate({
    required String agentId,
    required String methodId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(methodId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiAuthenticateConstMeta,
        argValues: [agentId, methodId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthenticateConstMeta => const TaskConstMeta(
    debugName: "authenticate",
    argNames: ["agentId", "methodId"],
  );

  @override
  Stream<String> crateApiClientRequestStream() {
    final sink = RustStreamSink<String>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_String_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiClientRequestStreamConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiClientRequestStreamConstMeta =>
      const TaskConstMeta(
        debugName: "client_request_stream",
        argNames: ["sink"],
      );

  @override
  Future<String> crateApiCoreInit({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiCoreInitConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreInitConstMeta =>
      const TaskConstMeta(debugName: "core_init", argNames: ["dataDir"]);

  @override
  BigInt crateApiDroppedEventCount() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDroppedEventCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDroppedEventCountConstMeta =>
      const TaskConstMeta(debugName: "dropped_event_count", argNames: []);

  @override
  Future<String> crateApiFsListDir({
    required String root,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFsListDirConstMeta,
        argValues: [root, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsListDirConstMeta =>
      const TaskConstMeta(debugName: "fs_list_dir", argNames: ["root", "path"]);

  @override
  Future<String> crateApiFsSearch({
    required String root,
    required String query,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiFsSearchConstMeta,
        argValues: [root, query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFsSearchConstMeta => const TaskConstMeta(
    debugName: "fs_search",
    argNames: ["root", "query", "limit"],
  );

  @override
  Future<String> crateApiGitBranches({required String cwd}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cwd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiGitBranchesConstMeta,
        argValues: [cwd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitBranchesConstMeta =>
      const TaskConstMeta(debugName: "git_branches", argNames: ["cwd"]);

  @override
  Future<String> crateApiGitCreateBranch({
    required String cwd,
    required String branch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cwd, serializer);
          sse_encode_String(branch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiGitCreateBranchConstMeta,
        argValues: [cwd, branch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitCreateBranchConstMeta => const TaskConstMeta(
    debugName: "git_create_branch",
    argNames: ["cwd", "branch"],
  );

  @override
  Future<String> crateApiGitDiff({required String cwd, String? base}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cwd, serializer);
          sse_encode_opt_String(base, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiGitDiffConstMeta,
        argValues: [cwd, base],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitDiffConstMeta =>
      const TaskConstMeta(debugName: "git_diff", argNames: ["cwd", "base"]);

  @override
  Future<String> crateApiGitSwitch({
    required String cwd,
    required String branch,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cwd, serializer);
          sse_encode_String(branch, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiGitSwitchConstMeta,
        argValues: [cwd, branch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGitSwitchConstMeta =>
      const TaskConstMeta(debugName: "git_switch", argNames: ["cwd", "branch"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiPing({required String echo}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(echo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiPingConstMeta,
        argValues: [echo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: ["echo"]);

  @override
  Future<String> crateApiSessionCancel({
    required String agentId,
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSessionCancelConstMeta,
        argValues: [agentId, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionCancelConstMeta => const TaskConstMeta(
    debugName: "session_cancel",
    argNames: ["agentId", "sessionId"],
  );

  @override
  Future<String> crateApiSessionIndexList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSessionIndexListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionIndexListConstMeta =>
      const TaskConstMeta(debugName: "session_index_list", argNames: []);

  @override
  Future<String> crateApiSessionIndexRemove({
    required String agentId,
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSessionIndexRemoveConstMeta,
        argValues: [agentId, sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionIndexRemoveConstMeta => const TaskConstMeta(
    debugName: "session_index_remove",
    argNames: ["agentId", "sessionId"],
  );

  @override
  Future<String> crateApiSessionIndexUpsert({required String entry}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(entry, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSessionIndexUpsertConstMeta,
        argValues: [entry],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionIndexUpsertConstMeta => const TaskConstMeta(
    debugName: "session_index_upsert",
    argNames: ["entry"],
  );

  @override
  Future<String> crateApiSessionNew({
    required String agentId,
    required String cwd,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(cwd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSessionNewConstMeta,
        argValues: [agentId, cwd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionNewConstMeta => const TaskConstMeta(
    debugName: "session_new",
    argNames: ["agentId", "cwd"],
  );

  @override
  Future<String> crateApiSessionPrompt({
    required String agentId,
    required String sessionId,
    required String prompt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(prompt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSessionPromptConstMeta,
        argValues: [agentId, sessionId, prompt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionPromptConstMeta => const TaskConstMeta(
    debugName: "session_prompt",
    argNames: ["agentId", "sessionId", "prompt"],
  );

  @override
  Future<String> crateApiSessionSetConfigOption({
    required String agentId,
    required String sessionId,
    required String configId,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(configId, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSessionSetConfigOptionConstMeta,
        argValues: [agentId, sessionId, configId, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSetConfigOptionConstMeta =>
      const TaskConstMeta(
        debugName: "session_set_config_option",
        argNames: ["agentId", "sessionId", "configId", "value"],
      );

  @override
  Future<String> crateApiSessionSetMode({
    required String agentId,
    required String sessionId,
    required String modeId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_String(modeId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSessionSetModeConstMeta,
        argValues: [agentId, sessionId, modeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionSetModeConstMeta => const TaskConstMeta(
    debugName: "session_set_mode",
    argNames: ["agentId", "sessionId", "modeId"],
  );

  @override
  Stream<String> crateApiSessionUpdateStream() {
    final sink = RustStreamSink<String>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_String_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiSessionUpdateStreamConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSessionUpdateStreamConstMeta =>
      const TaskConstMeta(
        debugName: "session_update_stream",
        argNames: ["sink"],
      );

  @override
  Future<String> crateApiTerminalAuthRun({
    required String agentId,
    required String methodId,
    required String cwd,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(agentId, serializer);
          sse_encode_String(methodId, serializer);
          sse_encode_String(cwd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiTerminalAuthRunConstMeta,
        argValues: [agentId, methodId, cwd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalAuthRunConstMeta => const TaskConstMeta(
    debugName: "terminal_auth_run",
    argNames: ["agentId", "methodId", "cwd"],
  );

  @override
  Stream<String> crateApiTerminalOutputStream() {
    final sink = RustStreamSink<String>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_String_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiTerminalOutputStreamConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTerminalOutputStreamConstMeta =>
      const TaskConstMeta(
        debugName: "terminal_output_stream",
        argNames: ["sink"],
      );

  @override
  Future<String> crateApiTerminalWrite({
    required String terminalId,
    required String data,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(terminalId, serializer);
          sse_encode_String(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiTerminalWriteConstMeta,
        argValues: [terminalId, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalWriteConstMeta => const TaskConstMeta(
    debugName: "terminal_write",
    argNames: ["terminalId", "data"],
  );

  @override
  Stream<String> crateApiTrafficStream() {
    final sink = RustStreamSink<String>();
    handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_StreamSink_String_Sse(sink, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiTrafficStreamConstMeta,
        argValues: [sink],
        apiImpl: this,
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTrafficStreamConstMeta =>
      const TaskConstMeta(debugName: "traffic_stream", argNames: ["sink"]);

  @override
  Future<String> crateApiWorkspaceOpen({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiWorkspaceOpenConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceOpenConstMeta =>
      const TaskConstMeta(debugName: "workspace_open", argNames: ["path"]);

  @override
  Future<String> crateApiWorkspaceRecent() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_bridge_error,
        ),
        constMeta: kCrateApiWorkspaceRecentConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceRecentConstMeta =>
      const TaskConstMeta(debugName: "workspace_recent", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final var_code = sse_decode_String(deserializer);
    final var_message = sse_decode_String(deserializer);
    return BridgeError(code: var_code, message: var_message);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    final len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
